import React from "react";
import axios from "axios";


function App(){
    function loadScript(src){
        
    }


    async function displayRazorpay(){
        // we will call our backedn
    }

    const options={

    }

    return(
        <>
            <header>
                <img></img>
                <p>Buy Now</p>
                <button onClick={displayRazorpay}>
                    Pay 500 Rupya
                </button>
            </header>
        </>
    );
}

